Landing page
Avin008/saiyan-component-library pull request #13
Opened 2022-02-15 12:24 UTC by Avin008

### Landing Page Includes: 

![landing](https://user-images.githubusercontent.com/32406268/154061497-0b6e0265-4193-4af2-90bb-b7468aab78c3.PNG)

2022-02-15 14:41 UTC, Manju-sree requested changes
better to use one type of class declarations in whole file. rest code looks fine..

2022-02-15 14:41 UTC, Manju-sree commented on index.html
> +              class="jumbotron__btn jumbotron__btn--secondary"
same here

2022-02-15 15:49 UTC, Avin008 commented on index.html
> +              class="jumbotron__btn jumbotron__btn--secondary"
Here I'm using jumbotron__btn--secondary as a modifier class. Can you plz approve the changes

2022-02-16 11:54 UTC, Manju-sree approved these changes
LGTM

2022-02-16 11:54 UTC, Manju-sree commented on index.html
> +              class="jumbotron__btn jumbotron__btn--secondary"
okay, it's looks fine now, you can go ahead with merge

2022-02-20 19:00 UTC, merged